apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-api
  template:
    metadata:
      labels:
        app: task-api
      # Adding an annotation with a timestamp forces a new rollout if needed
      annotations:
        redeploy-timestamp: "{{ timestamp }}"
    spec:
      containers:
      - name: task-api
        image: leolr10/task-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_URI
          value: "mongodb://mongodb-service:27017/yourdbname"
---
apiVersion: v1
kind: Service
metadata:
  name: task-api-service
spec:
  type: NodePort
  selector:
    app: task-api
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080
