name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-deploy:
    name: Build and Deploy Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Backend with Maven
        working-directory: task-api
        run: mvn clean package

      - name: Build Docker Image for Backend
        working-directory: task-api
        run: docker build -t leolr10/task-api:latest .

      - name: Login to Docker Hub (Backend)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image for Backend
        working-directory: task-api
        run: docker push leolr10/task-api:latest

      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_B64 }}" | base64 --decode > $HOME/.kube/config
          cat $HOME/.kube/config  # (Optional) For debugging, remove in production
        env:
          KUBECONFIG_B64: ${{ secrets.KUBECONFIG_B64 }}

      - name: Verify Kubeconfig
        run: kubectl cluster-info
        env:
          KUBECONFIG: $HOME/.kube/config

      - name: Deploy MongoDB to Kubernetes
        run: kubectl apply -f task-api/kubernetes/mongodb.yaml --validate=false
        env:
          KUBECONFIG: $HOME/.kube/config

      - name: Deploy Backend to Kubernetes
        run: kubectl apply -f task-api/kubernetes/app.yaml
        env:
          KUBECONFIG: $HOME/.kube/config

  frontend-deploy:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest
    needs: backend-deploy
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Frontend Dependencies
        working-directory: task-ui
        run: npm install

      - name: Build Frontend
        working-directory: task-ui
        run: npm run build

      - name: Build Docker Image for Frontend
        working-directory: task-ui
        run: docker build -t leolr10/task-ui:latest .

      - name: Login to Docker Hub (Frontend)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image for Frontend
        working-directory: task-ui
        run: docker push leolr10/task-ui:latest

      # Optional: Deploy frontend to Kubernetes if desired
      # - name: Deploy Frontend to Kubernetes
      #   run: kubectl apply -f task-ui/kubernetes/app.yaml
      #   env:
      #     KUBECONFIG: $HOME/.kube/config
